server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: shop-payment

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yunshen.shop.entity
